### ISSUE TITLE
How to fetch value of seven segment view

### ISSUE THREAD

**Issue by hoomanhooshyar** [JackHurst0/seven-segment-display#1]
Thanks a lot for your useful library
I have used this library and now I want to fetch the value of the digits?
I could not find something like getDigits or something like this

**Comment by JackHurst0** [comment]
Hi @hoomanhooshyar, thanks for using the library! The library currently does not support a method like this, however I can see how it would be useful. I will look into giving you a release this weekend which has that functionality.

**Comment by JackHurst0** [comment]
@hoomanhooshyar 

Update to version 0.0.2 and you will be able to access and set the digits of the view as a property of the view. Note that the way digits are set on views has now changed.

Previously:
`view.setDigits(5)`
Now:
`view.digits = 5`
